### ISSUE TITLE
How do you load the cc12m dataset?

### ISSUE THREAD

**Issue by lez-s** [Zi-hao-Wei/Masking-Clusters-in-Vision-language-Pretraining#1]
Sorry, I don't quite know how to use the cc12m dataset to pretrain.  The data downloaded by `img2dataset` is `00000.tar/json/parquet`~`01242.tar/json/parquet`. 
`--train-data="/cc12m_folder/"` and  `--train-data="/cc12m.tsv"` don't work neither.

**Comment by Zi-hao-Wei** [comment]
I am not sure you are downloading the cc12m correctly. It shouldn't end with some temp dir, but '.tar' instead.
